import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('SQL masivo: RLS, rollback, tenant, permisos, versiones y fusión sin duplicación', async () => {
  const db = new PGlite();
  const tenant='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
  const first='00000000-0000-4000-8000-000000000011',second='00000000-0000-4000-8000-000000000012';
  try {
    await db.exec(`create role authenticated;create role anon;create schema auth;
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
      create function public.can_access_tenant(t uuid) returns boolean language sql stable as $$select t=nullif(current_setting('test.tenant',true),'')::uuid$$;
      create table beneficiario(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,nombre text,estado_panuelo text,updated_at timestamptz default now());
      create table pre_encargo_tienda(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,estado text not null check(estado<>'invalid'),monto_pagado numeric default 0,updated_at timestamptz default now());
      alter table beneficiario enable row level security;alter table pre_encargo_tienda enable row level security;
      create policy own on beneficiario for all to authenticated using(can_access_tenant(tenant_id)) with check(can_access_tenant(tenant_id));
      create policy own on pre_encargo_tienda for all to authenticated using(can_access_tenant(tenant_id)) with check(can_access_tenant(tenant_id));
      create policy writable on pre_encargo_tienda as restrictive for update to authenticated using(current_setting('test.write',true)='yes');
      grant usage on schema public,auth to authenticated,anon;
      grant select,insert,update on beneficiario,pre_encargo_tienda to authenticated;
      insert into beneficiario(id,tenant_id,nombre) values('${first}','${tenant}','Ficticio'),('${second}','${other}','Otro grupo');
      insert into pre_encargo_tienda(id,tenant_id,estado) values('${first}','${tenant}','Pendiente'),('${second}','${tenant}','Pendiente');
      set test.uid='${first}';set test.tenant='${tenant}';set test.write='yes';`);
    const sql=await readFile(new URL('../../../supabase/migrations/202609140001_atomic_tenant_batches.sql',import.meta.url),'utf8');
    await db.exec(sql);await db.exec(sql);
    await db.exec('set role authenticated');
    const apply=(table,ops,t=tenant)=>db.query('select apply_tenant_batch($1,$2,$3) as rows',[t,table,JSON.stringify(ops)]);
    const update=(id,values)=>({type:'update',id,values});
    await apply('beneficiario',[update(first,{estado_panuelo:'Sí'})]);
    assert.equal((await db.query('select estado_panuelo from beneficiario')).rows[0].estado_panuelo,'Sí');
    await assert.rejects(apply('beneficiario',[update(first,{estado_panuelo:'NO'}),update(second,{estado_panuelo:'NO'})]));
    assert.equal((await db.query('select estado_panuelo from beneficiario')).rows[0].estado_panuelo,'Sí');
    await assert.rejects(apply('beneficiario',[update(first,{estado_panuelo:'NO'})],other));
    await assert.rejects(apply('beneficiario',[update(first,{tenant_id:other})]));
    await assert.rejects(apply('beneficiario',[update(first,{id:second})]));
    await assert.rejects(apply('beneficiario',[update(first,{unknown:'x'})]));
    await assert.rejects(apply('beneficiario',[update(first,{nombre:'x'}),update(first,{nombre:'y'})]));
    await assert.rejects(apply('profiles',[update(first,{nombre:'x'})]));
    await assert.rejects(apply('beneficiario',[]));
    await assert.rejects(apply('pre_encargo_tienda',[update(first,{estado:'Confirmado'}),update(second,{estado:'invalid'})]));
    assert.deepEqual((await db.query('select estado from pre_encargo_tienda')).rows.map(r=>r.estado),['Pendiente','Pendiente']);
    await db.exec("set test.write='no'");
    await assert.rejects(apply('pre_encargo_tienda',[update(first,{estado:'Confirmado'})]));
    await db.exec("set test.write='yes'");
    const version=(await db.query('select updated_at::text as version from pre_encargo_tienda where id=$1',[first])).rows[0].version;
    const fusion=[{...update(first,{estado:'Cancelado',monto_pagado:0}),expected_updated_at:version},{type:'create',values:{estado:'Pendiente',monto_pagado:10}}];
    const fused=await apply('pre_encargo_tienda',fusion);
    assert.equal(fused.rows[0].rows.length,2);
    await assert.rejects(apply('pre_encargo_tienda',fusion));
    assert.equal((await db.query('select count(*)::int as total from pre_encargo_tienda')).rows[0].total,3);
    const current=(await db.query('select updated_at::text as version from pre_encargo_tienda where id=$1',[second])).rows[0].version;
    await assert.rejects(apply('pre_encargo_tienda',[{...update(second,{estado:'Cancelado'}),expected_updated_at:current},{type:'create',values:{estado:'invalid'}}]));
    assert.equal((await db.query('select estado from pre_encargo_tienda where id=$1',[second])).rows[0].estado,'Pendiente');
    await db.exec("set test.uid=''");
    await assert.rejects(apply('beneficiario',[update(first,{nombre:'x'})]));
    await db.exec('reset role;set role anon');
    await assert.rejects(apply('beneficiario',[update(first,{nombre:'x'})]));
  } finally { await db.close(); }
});
